# Created using Apache Ant script from Japplis
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Japplis.AppletRunnerPro
PackageVersion: 2.19
Platform:
- Windows.Desktop
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://www.japplis.com/applet-runner/pro/versions/AppletRunnerPro-2.19.exe
  InstallerSha256: 861046ed90a0d03ed9f9b56b12f12628f291a89890e5fc9db1612c3d79723211
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  Scope: user
  InstallerUrl: https://www.japplis.com/applet-runner/pro/versions/AppletRunnerPro-2.19.exe
  InstallerSha256: 861046ed90a0d03ed9f9b56b12f12628f291a89890e5fc9db1612c3d79723211
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.10.0
