# Created using Apache Ant script from Japplis
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Japplis.Watch
PackageVersion: 1.5
PackageLocale: en-US
Publisher: Japplis
PublisherUrl: https://www.japplis.com
PackageName: Japplis Watch
PackageUrl: https://www.japplis.com/watch
License: Freeware
LicenseUrl: https://www.japplis.com/watch/license.txt
Copyright: Copyright © 2009 - 2023 Japplis. All rights reserved.
ShortDescription: Japplis Watch is a set of time utilities. 
It contains a clock, timer, stopwatch, alarm, calendar, time zone, countdown to date, server time and pomodoro/HIIT.
The window can remain always on top and be transparent.
ReleaseNotesUrl: https://www.japplis.com/watch/changes.txt
Tags: 
- watch
- clock
- timer
- stopwatch
- alarm
- calendar
- timezone
- countdown
- date
- time
- pomodoro
- HIIT
ManifestType: defaultLocale
ManifestVersion: 1.4.0


