# Created using Apache Ant script from Japplis
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Japplis.PostOnScreen.Pro
PackageVersion: 1.5
Platform:
- Windows.Desktop
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://www.japplis.com/post-on-screen/pro/versions/PostOnScreenPro-1.5.exe
  InstallerSha256: 9c333641cea6879ede6d11b37361f758394bb47222297ad27e02c1c3f6c14e5e
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  Scope: user
  InstallerUrl: https://www.japplis.com/post-on-screen/pro/versions/PostOnScreenPro-1.5.exe
  InstallerSha256: 9c333641cea6879ede6d11b37361f758394bb47222297ad27e02c1c3f6c14e5e
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.10.0
